### ISSUE TITLE
Does nightingale work in React Native / expo?

### ISSUE THREAD

**Issue by chmac** [christophehurpeau/nightingale#106]
Any idea if this works in React Native?

Saw a link to this package [here](https://github.com/onubo/react-native-logs/issues/12).

**Comment by christophehurpeau** [comment]
Hey @chmac,

I haven't tested it yet but I plan to, I have a new project with expo so it should be soon

**Comment by chmac** [comment]
@christophehurpeau Great. I'm using something home rolled at the moment, would be happy to switch out to a proper log framework. Let me know if I can help with testing, etc.

**Comment by christophehurpeau** [comment]
Hey @chmac, I released https://www.npmjs.com/package/nightingale-app-react-native and https://www.npmjs.com/package/nightingale-react-native-console last week and it seems to work well for me as dev logger, can you check it ? Let me know ! Do you need a specific handler for production usage ? I've tested [nightingale-sentry](https://www.npmjs.com/package/nightingale-sentry)

**Comment by chmac** [comment]
@christophehurpeau Awesome, thanks for this. I'll queue it to test during our next dev sprint, which is in 1.5 or 2.5 weeks. Will investigate and report back then. Thanks a lot.

**Comment by christophehurpeau** [comment]
Sorry I haven't heard from you @chmac , as I use often react-native with nightingale now I can close this issue. Please open an other issue if you encounter problems when you setup nightingale !

**Comment by chmac** [comment]
@christophehurpeau Understood. I have this on my list, but it hasn't so far reached the top unfortunately. I really appreciate the super fast turnaround on getting a react-native console logger implemented.

From looking a little at the code, it seems like the check for log level is synchronous here:

https://github.com/christophehurpeau/nightingale/blob/73a11abe126a69503711858e737120725bd2c3ca/packages/nightingale-browser-console/src/index.ts#L14-L16

React Native doesn't have a sync version of `localStorage` only its own async `AsyncStorage` which has a similar API. Is it possible to set the log level for nightingale from an async data source?

Ideally I'd be able to use the same approach as `DEBUG="..."` or `localStorage.DEBUG` but within React Native, where our only option seems to be async. I've got issues in my current home rolled logger because the first `log()` calls happen before the async settings have returned, and so I don't know at that point what should be logged and what shouldn't.

I really like that nightingale supports the DEBUG option, as we've used the `debug` package in a few of the packages we've published, so if we could wire them all up to a single method of enabling / disabling that would be ideal.

**Comment by christophehurpeau** [comment]
The code you are referring to is only used in react-native web, so you can use `localStorage.DEBUG` with react-native web (for example with expo web !)

Can you clarify: do you want support of `DEBUG="..."` for example when starting the app, or AsyncStorage to change the log, or maybe both ?

To have a `DEBUG` support from cli, the first step would be to import the DEBUG env variable with one of a technique described in this document: https://docs.expo.io/guides/environment-variables/. On nightingale side, I would need to add the same findDebugLevel thing in react-native's logger to make it work. However, you would need to restart and clear cache each time you want to change the `DEBUG` value ?

If you want to set the levels at runtime (for example a debug button that enables specific logs ?), you can reconfigure the loggers with the [`configure` function](https://github.com/christophehurpeau/nightingale/tree/master/packages/nightingale-app-react-native#change-default-levels), it will override existing configuration !

**Comment by chmac** [comment]
@christophehurpeau I've been giving this further thought. I think I'm conflating two goals:

* Interop with DEBUG
* Dynamic logger settings in React Native

The idea behind the first is that many people use the debug package, and so if I can use a logger which has the same method of activation, that makes life easier. Then I could also use this logger inside of published packages if it'll work the same way.

The second part is the stumbling block, and I'm coming to the conclusion that it's not possible. Ideally, I'd like the user to be able to toggle log levels within the app. However, React Native is a 100% async environment. There's simply no way to retrieve any kind of persisted state synchronously in javascript. As both debug and nightingale expect the log settings to be available immediately, I guess this is simply not going to work.

It's also a hard problem. If a logger can be configured after it is instantiated, what should it do with log messages received before the configuration event?

In reality, maybe I'm also creating problems where they don't exist. The only issue here will be if we need to debug the startup process of the app. Otherwise, changing log levels, etc after the app is already running would be acceptable.

Thanks again for the feedback. I'll load the logger now and run some tests.

**Comment by christophehurpeau** [comment]
> I'd like the user to be able to toggle log levels within the app

For that case, I think one solution could be to persist the config asynchronously while changing the logger synchronously. For startup, I would say that maybe retrieve the persisted config as soon as possible, and maybe wait before doing anything else if you don't want to loose logs. That might affect startup speed then, but I think that getting stuff from AsyncStorage is pretty fast and you can maybe get all the things you need from async storage or load other async things while waiting for the logger to be setup ?

In any case, please do share what you came up with, it is a interesting problem :)

**Comment by chmac** [comment]
Yeah, that's what I was thinking also. To delay startup until I've done some init process that fetches the log level and sets up the logger.

I've started thinking of this as two separate issues. How to handle capturing `console.*` in production, and then logging in our codebase. I was trying to wrap them all into one topic which makes it a whole lot more complicated.

Will report back if I figure out a good solution here. Thanks a lot for all the input, I appreciate it.
