### ISSUE TITLE
Stack traces show LogSerialization.js in React Native in console

### ISSUE THREAD

**Issue by chmac** [christophehurpeau/nightingale#242]
Follow up from #241 where I noticed that nightingale logs the stack trace correctly in React Native Debugger, but the stack trace is somehow wrong. Or put differently, the text output I see in the console is correct, but the actual stack trace is wrong. I see the actual stack trace in 2 places, in my terminal and as an "expanding option" in the React Native Debugger console. Hopefully the screenshots make it clear.

This shows LogSerialization.js as the source of the error, which is where the log method was called:

<img width="627" alt="Screenshot 2021-05-14 at 12 43 38" src="https://user-images.githubusercontent.com/690997/118260014-1c7c0400-b4b2-11eb-996a-37436db03f18.png">

While in the React Native Debugger console, I see the correct stack trace:

<img width="484" alt="image" src="https://user-images.githubusercontent.com/690997/118260193-47665800-b4b2-11eb-83a5-2c899936b80f.png">

Note that this log message has a > option at the left which I can click to expand the attached stack trace, that expanded stack trace looks like this:

<img width="386" alt="image" src="https://user-images.githubusercontent.com/690997/118260288-62d16300-b4b2-11eb-9665-639da2f68996.png">

I don't know enough about stack traces and React Native to provide much useful input here. I guess that somehow the text of the log message is being correctly generated from the real stack trace, but somehow by the time the `console.*()` call has been shipped over the wire from the device to the host computer, the stack has been borked.

Perhaps this is "good enough". At least it's very helpful to see the actual stack trace in the log message. If memory serves, I often see meaningless stack traces when exceptions are thrown without nightingale in the chain. Not sure if this issue is useful or not, just wanted to share in case it's helpful, feel free to close without comment.

**Comment by christophehurpeau** [comment]
hey, I added some documentation on how to get proper stack traces with react-native https://github.com/christophehurpeau/nightingale/blob/f063b9ecb656e36eda1f112a7222acf52c823749/packages/nightingale-app-react-native/README.md#use-source-maps-to-display-error-stack-trace but rereading this issue it seems to be specific to React Native Debugger, so let me keep it open while I investigate this

**Comment by christophehurpeau** [comment]
oh wait no, so it's in the console that it's wrong but not in React Native Debugger

**Comment by christophehurpeau** [comment]
So the 'Fatal Level Message' that you are login is not an Error ?
To display the stack trace, you should log an Error and not just a string

```
appLogger.error('something fatal happened', { error: new Error('error message') })
```

You will get 2 stacks: the one logged by nightingale, which is the stack of the error
and the one logged by react-native witch shows who used `console.error`

Maybe for react-native nightingale should stick with `console.log` to avoid theses stack traces ?

![image](https://user-images.githubusercontent.com/302891/124038427-6472ce00-da01-11eb-9c6d-4d3716ff515c.png)

**Comment by chmac** [comment]
@christophehurpeau The advantage of the real stack trace is that the code points becomes clickable. So if I want to know what is going on, I can click the filename and jump to that point. I guess that nightingale is somehow capturing a stack trace, and then rendering it to a string. This string is then included in the log message. But that string is not understood by the dev tools at all, so it's not clickable.

You're probably right that using `console.log()` would remove the bogus stack trace. If it were possible to show the correct stack trace in the output, that would be even better I think. But I don't know enough about how the `console.*` methods work to know how achievable that is...
